#!/usr/bin/env bash

source ./includes/functions

if [[ is_platform_mac && "${__BASH_HAVE_DEFAULTS:-0}" == "0" ]]; then
  copy_with_backup ./.bash_defaults ~/.bash_defaults

  # The below requires that .bash_profile exists, even if it's empty
  touch ~/.bash_profile

  echo "[ -f ~/.bash_defaults ] && source ~/.bash_defaults" | cat - ~/.bash_profile > /tmp/.bash_profile.tmp && mv /tmp/.bash_profile.tmp ~/.bash_profile
fi
