#!/usr/bin/env bash

source ./includes/functions

if ! command_exists "git"; then
  echo "Could not find 'git' command."
  echo
  echo "Please verify your git installation before running this script."

  exit 1
fi

set_git_colors() {
  git config --global color.ui "true" &&
  git config --global color.branch.current "yellow reverse" &&
  git config --global color.branch.local "yellow" &&
  git config --global color.branch.remote "green" &&
  git config --global color.diff.meta "yellow bold" &&
  git config --global color.diff.frag "magenta bold" &&
  git config --global color.diff.old "red bold" &&
  git config --global color.diff.new "green bold" &&
  git config --global color.status.added "yellow" &&
  git config --global color.status.changed "green" &&
  git config --global color.status.untracked "cyan"
}

prompt_yes_no() {
  local response=$(prompt "$@")

  case "${response}" in
    y|yes)
      echo "yes"
      ;;
    n|no)
      echo "no"
      ;;
    *)
      echo "unknown"
    ;;
  esac
}

prompt() {
  local prompt_text=$1
  local result;

  read -p "${prompt_text} " result

  echo "${result}"
}

confirm_prompt_github() {
  local GITHUB_FULL_NAME=$1
  local GITHUB_EMAIL=$2
  local prompt_confirmed

  echo "The author section of your git activity will look like thiasdasds:"
  echo
  echo "  '${GITHUB_FULL_NAME} <${GITHUB_EMAIL}>'"
  echo
  read -p "Does that look correct? (y/n) " prompt_confirmed

  format_yesno_prompt "${prompt_confirmed}"
}

confirm_github_name_and_email() {
  local GITHUB_FULL_NAME=$(prompt "Enter your full name:")
  local GITHUB_EMAIL=$(prompt "Enter the email address you use on GitHub:")

  local prompt_confirmed=$(confirm_prompt_github "$GITHUB_FULL_NAME" "$GITHUB_EMAIL")

  echo "result is: ${prompt_confirmed}"

  case "$prompt_confirmed" in
    yes)
      return 0
      ;;
    no)
      echo "Ok, let's try again!"
      echo
      confirm_github_name_and_email
      ;;
    unknown)
      echo "Please enter y or n."
      echo
      confirm_github_name_and_email
      ;;
    esac
}

echo "Configuring git..."
set_git_colors

until [[ "${PROMPT_CONFIRMED}" == "yes" ]]; do
  echo
  GITHUB_FULL_NAME=$(prompt "Enter your full name:")
  GITHUB_EMAIL=$(prompt "Enter the email address you use on GitHub:")

  echo
  echo "The author section of your git activity will look like this:"
  echo
  echo "  '${GITHUB_FULL_NAME} <${GITHUB_EMAIL}>'"
  echo

  PROMPT_CONFIRMED=$(prompt_yes_no "Does that look correct? (y/n)")

  case "$PROMPT_CONFIRMED" in
    no)
      echo "Ok, let's try again!"
      ;;
    unknown)
      echo "Unknown response. Please confirm by entering y/n"
      ;;
  esac
done

echo "Setting git name and email..."

git config --global user.name "${GITHUB_FULL_NAME}"
git config --global user.email "${GITHUB_EMAIL}"
