#!/usr/bin/env bash

source ./includes/functions

if ! command_exists "git"; then
  echo "Could not find 'git' command."
  echo
  echo "Please verify your git installation before running this script."

  if is_platform_mac; then
    echo
    echo "Run the following command to install git:"
    echo "  brew install git"
  fi

  exit 1
fi

set_git_colors() {
  git config --global color.ui "true" &&
  git config --global color.branch.current "yellow reverse" &&
  git config --global color.branch.local "yellow" &&
  git config --global color.branch.remote "green" &&
  git config --global color.diff.meta "yellow bold" &&
  git config --global color.diff.frag "magenta bold" &&
  git config --global color.diff.old "red bold" &&
  git config --global color.diff.new "green bold" &&
  git config --global color.status.added "yellow" &&
  git config --global color.status.changed "green" &&
  git config --global color.status.untracked "cyan"
}

set_git_aliases() {
  git config --global alias.st "status -s" &&
  git config --global alias.co "checkout" &&
  git config --global alias.br "branch" &&
  git config --global alias.hist "log --graph --date=short --pretty=format:\"%Cred%h%Creset | %Cgreen%ad%Creset | %Cblue[%an]%Creset %s%d\""
}

set_git_name_and_email() {
  if [[ $# -lt 2 ]]; then
    echo "set_git_name_and_email requires two arguments"
    return 1
  fi

  let name="$1"
  let email="$2"

  git config --global user.name "${name}" &&
  git config --global user.email "${email}"
}

confirm_prompt_github() {
  local GITHUB_FULL_NAME=$1
  local GITHUB_EMAIL=$2
  local prompt_confirmed

  echo "The author section of your git activity will look like this:"
  echo
  echo "  '${GITHUB_FULL_NAME} <${GITHUB_EMAIL}>'"
  echo
  read -p "Does that look correct? (y/n) " prompt_confirmed

  format_yesno_prompt "${prompt_confirmed}"
}

confirm_github_name_and_email() {
  local GITHUB_FULL_NAME=$(prompt "Enter your full name:")
  local GITHUB_EMAIL=$(prompt "Enter the email address you use on GitHub:")

  local prompt_confirmed=$(confirm_prompt_github "$GITHUB_FULL_NAME" "$GITHUB_EMAIL")

  case "$prompt_confirmed" in
    yes)
      return 0
      ;;
    no)
      echo "Ok, let's try again!"
      echo
      confirm_github_name_and_email
      ;;
    unknown)
      echo "Please enter y or n."
      echo
      confirm_github_name_and_email
      ;;
    esac
}

if guard "Setting colors for 'git status' command..." set_git_colors; then
  echo "Error running 'git config'"
  echo
  echo "Something is unusual about your environment and we are"
  echo "going to stop getting up git automatically."

  exit 1
fi

if guard "Adding git aliases..." set_git_aliases; then
  echo "Error running 'git alias'"
  echo
  echo "Something is unusual about your environment and we are"
  echo "going to stop getting up git automatically."

  exit 1
fi

until [[ "${PROMPT_CONFIRMED}" == "yes" ]]; do
  echo
  GITHUB_FULL_NAME=$(prompt "Enter your full name:")
  GITHUB_EMAIL=$(prompt "Enter the email address you use on GitHub:")

  echo
  echo "The author section of your git activity will look like this:"
  echo
  echo "  '${GITHUB_FULL_NAME} <${GITHUB_EMAIL}>'"
  echo

  PROMPT_CONFIRMED=$(prompt_yes_no "Does that look correct? (y/n)")

  case "$PROMPT_CONFIRMED" in
    no)
      echo "Ok, let's try again!"
      ;;
    unknown)
      echo "Unknown response. Please confirm by entering y/n"
      ;;
  esac
done

echo "Setting git name and email..."

if guard "Setting git name and email..." set_git_name_and_email "${GITHUB_FULL_NAME}" "${GITHUB_EMAIL}"; then
  echo "Error running 'git config'"
  echo
  echo "Something is unusual about your environment and we are"
  echo "going to stop getting up git automatically."

  exit 1
fi
